DROP TYPE IF EXISTS rating_num;
CREATE TYPE rating_num AS ENUM (
  '1',
  '2',
  '3',
  '4',
  '5'
);

CREATE TABLE bookmark_items (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  title TEXT NOT NULL,
  url TEXT NOT NULL,
  description TEXT,
  rating rating_num NOT NULL
);